openapi: 3.0.0
info:
  title: Product Search API
  description: An API to search for products
  version: 1.0.0
  contact:
    name: NickyHariniaina
    email: nickyharini1na@gmail.com

servers:
  - url: http://localhost:3000
    description: LocalHost server

paths:
  /products:
    get:
      tags:
        - Product
      summary: Get a list of products found
      parameters:
        - $ref: "#/components/parameters/LimitQuery"
        - $ref: "#/components/parameters/SearchQuery"
      responses:
        "200":
          description: A list of products
          content:
            application/json:
              examples:
                emptyList:
                  $ref: "#/components/examples/EmptyProduct"
                productList:
                  $ref: "#/components/examples/ManyProduct"
  /orders:
    get:
      tags:
        - Orders
      summary: A list of orders
      responses:
        "200":
          description: A list of orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Order"
              examples:
                AllOrders:
                  value:
                    - identifier: 2
                      customer_name: Nicky
                      creation_datetime: 2025-09-01 09:53
                      total_amount: 399.3
                    - identifier: 3
                      customer_name: Hariniaina
                      creation_datetime: 2025-09-01 09:53
                      total_amount: 233.9
    post:
      tags:
        - Orders
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Order"
      summary: Create an order
      responses:
        "201":
          description: Create a reponse
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: Order created
components:
  schemas:
    Order:
      type: object
      properties:
        identifier:
          type: integer
        customer_name:
          type: string
        creation_datetime:
          type: string
          format: datetime
        total_amount:
          type: integer
          format: float
      example:
        identifier: 1
        customer_name: Nicky
        creation_datetime: 2025-09-01 09:43
        total_amount: 4000.45
    Product:
      type: object
      properties:
        name:
          type: string
        expiration_datetime:
          type: string
          format: date-time
        price:
          type: number
          format: float
      example:
        name: Iphone 23
        expiration_datetime: 2025-09-01 09:20
        price: 23.45
  parameters:
    LimitQuery:
      name: limit
      description: Maximum number of elements
      in: query
      required: false
      schema:
        type: integer
      example: 23
    SearchQuery:
      name: q
      in: query
      description: A search term
      schema:
        type: string
      example: phone
  examples:
    ManyProduct:
      summary: A list of product found
      value:
        - name: Laptop 23nd generation
          expiration_datetime: 2025-09-01 09:29
          price: 30000.34
        - name: Iphone 75
          expiration_datetime: 2025-09-03 09:34
          price: 23.45
    EmptyProduct:
      summary: An empty list of product
      value: []
