openapi: 3.0.0
info:
  title: Best Practice OAS
  description: An OAS for BP
  version: 1.0.0
  contact:
    name: NickyHariniaina
    email: nickyharini1na@gmail.com

servers:
  - url: http://localhost:8080
    description: Localhost servers

paths:
  /users/{id}:
    get:
      summary: Get user by id with all information
      parameters:
        - $ref: "#/components/parameters/IdParam"
      responses:
        "200":
          description: Get user by id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserProfile"
              examples:
                userExample:
                  $ref: "#/components/examples/UserProfileExample"
  /users:
    post:
      summary: Create users without identifier
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/CreateUserProfile"
            example:
              - first_name: Nicky
                last_name: Hariniaina
                birthdate: 2007-04-12
                email: nickyharini1na@gmail.com
                address_street: lot II 45
                address_city: Ivandry
                address_country: Antananarivo
                address_postal_code: 101
                needs_newsletter: true
                language: fr
              - first_name: John
                last_name: Doe
                birthdate: 2007-04-12
                email: jD@gmail.com
                address_street: lot II 45
                address_city: Ivandry
                address_country: Antananarivo
                address_postal_code: 101
                needs_newsletter: true
                language: fr
      responses:
        "201":
          description: List of created user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CreateUserProfile"
              examples:
                userExample:
                  $ref: "#/components/examples/CreateUserProfileExample"
  /users/{id}/personalInfo:
    put:
      summary: Update only the personal information
      parameters:
        - $ref: "#/components/parameters/IdParam"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PersonalInfo"
            examples:
              personalInfoExample:
                $ref: "#/components/examples/PersonalInfoExample"
      responses:
        "200":
          description: Updated personal information
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PersonalInfo"
              examples:
                personalInfoExample:
                  $ref: "#/components/examples/PersonalInfoExample"

  /users/{id}/address:
    put:
      summary: Update only the address
      parameters:
        - $ref: "#/components/parameters/IdParam"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Address"
            examples:
              addressExample:
                $ref: "#/components/examples/AddressExample"
      responses:
        "200":
          description: Updated address
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Address"
              examples:
                addressExample:
                  $ref: "#/components/examples/AddressExample"
  /users/{id}/preferences:
    put:
      summary: Update only the preferences
      parameters:
        - $ref: "#/components/parameters/IdParam"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Preferences"
            examples:
              preferencesExample:
                $ref: "#/components/examples/PreferencesExample"
      responses:
        "200":
          description: Updated preferences
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Preferences"
              examples:
                preferencesExample:
                  $ref: "#/components/examples/PreferencesExample"

components:
  examples:
    PersonalInfoExample:
      value:
        first_name: Nicky
        last_name: Hariniaina
        birthdate: 2007-04-12
        email: nickyharini1na@gmail.com

    UserProfileExample:
      value:
        identifier: 1
        first_name: Nicky
        last_name: Hariniaina
        birthdate: 2007-04-12
        email: nickyharini1na@gmail.com
        address_street: lot II 45
        address_city: Ivandry
        address_country: Antananarivo
        address_postal_code: 101
        needs_newsletter: true
        language: fr
    CreateUserProfileExample:
      value:
        - first_name: Nicky
          last_name: Hariniaina
          birthdate: 2007-04-12
          email: nickyharini1na@gmail.com
          address_street: lot II 45
          address_city: Ivandry
          address_country: Antananarivo
          address_postal_code: 101
          needs_newsletter: true
          language: fr
        - first_name: John
          last_name: Doe
          birthdate: 2007-04-12
          email: jD@gmail.com
          address_street: lot II 45
          address_city: Ivandry
          address_country: Antananarivo
          address_postal_code: 101
          needs_newsletter: true
          language: fr

    AddressExample:
      value:
        address_street: lot II 45
        address_city: Ivandry
        address_country: Antananarivo
        address_postal_code: 101
    PreferencesExample:
      value:
        needs_newsletter: true
        language: fr
  schemas:
    PersonalInfo:
      type: object
      properties:
        first_name:
          type: string
          example: Nicky
        last_name:
          type: string
          example: Hariniaina
        birthdate:
          type: string
          format: date
          example: 2007-04-12
        email:
          type: string
          example: nickyharini1na@gmail.com
    Address:
      type: object
      properties:
        address_street:
          type: string
          example: lot II 45
        address_city:
          type: string
          example: Ivandry
        address_country:
          type: string
          example: Antananarivo
        address_postal_code:
          type: integer
          example: 101
    Preferences:
      type: object
      properties:
        needs_newsletter:
          type: boolean
          example: true
        language:
          type: string
          enum:
            - mg
            - fr
            - eng
    UserProfile:
      allOf:
        - type: object
          properties:
            identifier:
              type: integer
              example: 1
        - $ref: "#/components/schemas/PersonalInfo"
        - $ref: "#/components/schemas/Address"
        - $ref: "#/components/schemas/Preferences"
    CreateUserProfile:
      allOf:
        - $ref: "#/components/schemas/PersonalInfo"
        - $ref: "#/components/schemas/Address"
        - $ref: "#/components/schemas/Preferences"
  parameters:
    IdParam:
      name: id
      in: path
      description: identifier
      required: true
      schema:
        type: integer
        example: 2
